#!/bin/bash
qemu-system-riscv64 \
    -machine virt \
    -nographic \
    -bios ../../bootloader/rustsbi-qemu.bin \
    -device loader,file=target/riscv64gc-unknown-none-elf/release/os.bin,addr=0x80200000
