#!/bin/bash
echo "press [Ctrl+a], then press [x] to quit QEMU"
mkdir -p target
riscv64-unknown-elf-as -g -o target/first.o first.s
riscv64-unknown-elf-ld -T default.lds -o target/first target/first.o
qemu-system-riscv64 \
    -machine virt \
    -nographic \
    -bios none \
    -kernel target/first \
    -s -S
