#!/bin/bash
echo "press [Ctrl+a], then press [x] to quit QEMU"
mkdir -p target
riscv64-unknown-elf-as -g -o target/hello.o hello.s
riscv64-unknown-elf-ld -T default.lds -o target/hello target/hello.o
qemu-system-riscv64 \
    -machine virt \
    -nographic \
    -bios none \
    -kernel target/hello
